#!/bin/bash

killall -9 jackdbus
jack_control stop
killall -9 jackdbus
jack_control dps shorts False
jack_control ds alsa
jack_control dps rate 48000
jack_control eps realtime True
jack_control dps device 'hw:XUSB'
jack_control dps period 64
jack_control start

exit 0
