#!/bin/bash

source ~/bin/database/ide

emvironment=home
[ -n "$1" ] && [ -n "${!1}" ] && { environment="$1"; shift; }
name="[IDE :: ${!environment##*/}]"
exec st "$@" -n "$name" -t "$name" -T "$name" -e bash ~/bin/ide.helper.sh "${!environment}"
