#!/bin/bash

if [ $# -lt 1 ] 
then
	echo "usage: $0 pause/start"
	exit 1
fi

if [ "$1" = "pause" ]
then
	kill -STOP `ps -a | grep xautolock | sed -E 's/^\s+([0-9]+)\s+.*/\1/g'`
else 
	if [ "$1" = "start" ]
	then 
		kill -CONT `ps -a | grep xautolock | sed -E 's/^\s+([0-9]+)\s+.*/\1/g'`
	else
		echo "usage: $0 pause/start"
		exit 1
	fi
fi

exit 0
